WIP modularised ICIC from the lab

diff --git a/local-playbooks/roles/setup-icic-deployer/templates/icic-setup.sh.j2 b/local-playbooks/roles/setup-icic-deployer/templates/icic-setup.sh.j2
--- a/local-playbooks/roles/setup-icic-deployer/templates/icic-setup.sh.j2
+++ b/local-playbooks/roles/setup-icic-deployer/templates/icic-setup.sh.j2
@@ -2,22 +2,29 @@
 # =================================================================
 # Licensed Materials - Property of IBM
 #
-# (c) Copyright IBM Corp. 2022 All Rights Reserved
+# (c) Copyright IBM Corp. 2024 All Rights Reserved
 #
 # US Government Users Restricted Rights - Use, duplication or
 # disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 # =================================================================
 #
 # icic-setup.sh
-# Set up ICIC to the z/VM system
+# Set up ICIC to the z/VM system - Ver5sion 2.0
 # - Script is deployed by Ansible (TBC)
 # - Run at boot time if ICIC is requested
+# - Updated for modularisation
 #
 
 # SMAPI credentials are the same each time so set once
 source /etc/zvmesi/settings.env
-# This URL will be generated by the web interface; it will be sourced from file created by the Portal
-fastvmurl=$(cat {{ webroot }}/.secret/.fastvmurl)
+
+# Setup some vars:
+# The version to be installed is in the file from the web server
+# The code is in a module file in the "content" directory
+icicver=$(cat {{ webroot }}/.secret/.icicver)
+modpath="/opt/content/icic-${icicver}.esi"
+icicpath="/opt/icic/${icicver}"
+
 # set the size of the minidisks needed
 mdsizeckd=10016             # This is 3390-9 less one cylinder
 mdsizefba=20971488          # This is 10GB less 32 blocks (8 pages)
@@ -123,6 +130,20 @@ else
   echo "SMAPI listener active, continuing..."
 fi
 
+# Set up the mount of the ICIC module content
+cat <<EOF >"/etc/auto.icic-install-${icicver}"
+${icicpath}  -fstype=squashfs,exec :${modpath}
+EOF
+cat <<EOF >"/etc/auto.master.d/icic-install-${icicver}.autofs"
+/-  /etc/auto.icic-install-${icicver}
+EOF
+systemctl reload autofs
+
+if ! ls ${icicpath}/icicimg.txt 2>/dev/null ; then
+  echo "ICIC content module file could not be mounted!"
+  exit 6
+fi
+
 # fetch our current IP address, and strip the netmask off the end
 myip=$(ip -br addr show dev encad0 | awk '{print $3}') # the devname in here has to be set using Ansible too
 tmpip=${myip%/*}
@@ -193,12 +214,12 @@ if [[ ${disktype} == "ECKD" ]]; then
   chccwdev --attribute raw_track_access=1 -e 1200,1201
 fi
 # Fetch the disk image file
-icicimg=$(curl "${fastvmurl}"/ICICIMG.txt 2>/dev/null)
+icicimg=$(cat "${icicpath}"/icicimg.txt 2>/dev/null)
 if [[ ${disktype} == "FBA" ]]; then
   icicimg=$(echo "${icicimg}" | sed -e 's/-/-fba-/g')
 fi
-echo "Fetching ${icicimg%.*} for restoration..."
-curl ${fastvmurl}/${icicimg} | zcat | tee \
+echo "Restoring ${icicimg%.*}..."
+zcat ${icicpath}/${icicimg} | tee \
 	>(dd of=/dev/$(lsdasd | grep 0.0.1200 | awk '{print $3}') bs=64k iflag=fullblock oflag=direct) \
 	| dd of=/dev/$(lsdasd | grep 0.0.1201 | awk '{print $3}') bs=64k iflag=fullblock oflag=direct
 sync;sync;sync
@@ -298,9 +319,9 @@ echo "${mgtip} ${icicmgt,,}.${DOMAIN} ${icicmgt,,}" >> /etc/hosts
 echo "${cmpip} ${iciccmp,,}.${DOMAIN} ${iciccmp,,}" >> /etc/hosts
 
 # Fetch the ICIC dependencies content and expand it
-icicdep=$(curl ${fastvmurl}/ICICDEP.txt 2>/dev/null)
-echo "Fetching ${icicdep%.*} for ICIC dependencies..."
-curl "${fastvmurl}"/"${icicdep}" 2>/dev/null | tar -C /var/www/html/ -zx
+icicdep=$(cat ${icicpath}/icicdep.txt 2>/dev/null)
+echo "Setting up ${icicdep%.*} for ICIC dependencies..."
+tar zxf ${icicpath}/${icicdep} /var/www/html/ 2>/dev/null
 
 # IPLing the management guest
 echo "Issuing a SMAPI IPL for the management guest..."
